language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t dockerhub21092018/docker-react -f Dockerfile.dev .

script:
  - docker run dockerhub21092018/docker-react npm run test -- --coverage